### PR TITLE
Enable building nvbio with cuda10 and runable on Volta

### PR DESCRIPTION
**Pull request by vmiheer**
Also add alternate repo.

### CODE REVIEW

**Comment by r-barnes** [comment]
This looks like a really great notice to add.

**Comment by vmiheer** [comment]
@r-barnes, does this look okay? Otherwise please suggest alternative I can modify 😃 .

**Comment by r-barnes** [comment]
@vmiheer : This looks much better. I think the only other problem is that we have your continuous integration commit on this PR. Ideally, we should build a separate branch on our repo and remove that specific change, and any others which wouldn't immediately translate to Nvidia, though this is the only one I can think of.

**Comment by r-barnes** [comment]
@vmiheer : Actually, could you close this pull request? I'll make a new one from `upstream_pull_request`.

Nvidia is changing who owns the NvBio project and it turns out I know the new owner, so it might streamline the pull if I'm able to manage it.

**Pull request closed without merging**
